server:
  port: 20001
# 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: coupon-calculation-serv

logging:
  level:
    com.artisan.coupon: debug

# 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

